import { Footer } from "../../components/Footer";
import { Navbar } from "../../components/Navbar";
import Provider from "../../components/Provider";
import "./globals.css";
import { Inter, Roboto, Roboto_Mono } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
});
const roboto_mono = Roboto_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning>
      <body className={`${roboto_mono.className} dark:bg-neutral-900 h-screen`}>
        <Provider>
          <Navbar />
          <div className="mb-auto"> {children}</div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
